name: Build and deploy

on:
  push:
    branches: [master]
    tags-ignore: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.x

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1

  build:
    needs: [lint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: tetafro
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/tetafro/timer:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ansible
        run: sudo apt install -y ansible

      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519

      - name: Deploy new image
        run: >
          ansible-playbook
          --private-key ~/.ssh/id_ed25519
          --inventory '${{ secrets.SSH_HOST }}:${{ secrets.SSH_PORT }},'
          --user ${{ secrets.SSH_USER }}
          ./playbook.yml
